version: '3'
services:
  app:
    container_name: folder_watcher
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile    
    volumes:
      - /mnt/busse/it/qc_db:/mnt/busse/it/qc_db
      - ./config.yaml:/app/config.yaml
      - ./folder_watcher.log:/app/folder_watcher.log
    user: root
    entrypoint: ["/app/main", "/mnt/busse/it/qc_db/2023 Database/Release Reports 2023"]